services:
  # 🐬 MySQL 8.0 #
  db:
    image: mylife-db:8.0
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: mylife-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mylife_mysql_data:/var/lib/mysql
    networks:
      - mylife-network

  # 🐍 FastAPI Backend #
  backend:
    image: mylife-backend:1.0.0
    environment:
      TZ: America/Sao_Paulo    
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mylife-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "mylife-backend"

    networks:
      - mylife-network

  cron:
    image: mylife-backend:1.0.0
    environment:
      TZ: America/Sao_Paulo    
    container_name: mylife-cron
    restart: always
    command: sh -c "/app/wait-for-db.sh && printenv > /etc/environment && cron -f"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - mylife-network

  # 🌐 Vite + React Frontend #
  frontend:
    image: mylife-frontend:1.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    container_name: mylife-frontend    
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - mylife-network


volumes:
  mylife_mysql_data:
    name: mylife-mysql-data

networks:
  mylife-network:
    name: mylife-network
    driver: bridge
